[build]
publish = "public"
command = "npm run build"

[context.production]
  environment = { CONTENTFUL_ENVIRONMENT = "master" }

[context.staging]
  environment = { CONTENTFUL_ENVIRONMENT = "staging" }
